language: android
sudo: required
jdk: oraclejdk8

android: 
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository

before_install:
  - chmod +x gradlew
  - pip install --user codecov    #Install codecov

script:
  - ./gradlew build

after_success:
  - codecov                       #Run codecov