language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ADB_INSTALL_TIMEOUT=10

android: 
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script:
  - ./gradlew --info connectedDebugAndroidTest | grep "com\.example\.vexillum\..* >"